resolver: lts-9.1
packages:
- '.'
- lib/gi-xlib
- lib/gi-gdkx11
extra-deps: [
  gi-gst-1.0.14,
  gi-gstvideo-1.0.14,
  haskell-gi-overloading-1.0,
  gi-gstbase-1.0.15
]
flags: {}
extra-package-dbs: []
